# População brasileira: 2010 e 2022

Agregações por estado e município, ordenadas pela variação absoluta da população entre 2010 e 2022.

In [3]:
!pip install pandas
!pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-3.0.5-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.5.3-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\program files\python312\lib\site-packages (from pandas) (2.8.2)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.4-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\program files\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-3.0.5-cp312-cp312-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB 1.3 MB/s eta 0:00:08
   ---------------------------------------- 0.1/9.8 MB 1.1 MB/s eta 0:00:10
    --------------------------------------- 0.2/9.8 MB 1.9 MB/s eta 0:00:06
   - -------------------------------------- 0.5/9.8 MB 2.6 MB/s eta 0:00:04
   --- ------------------------------------ 0.9/9.8 MB 3.9 MB/s eta 0:00:03
   ------ --------------------------------- 1.7/9.8 MB 6.0 MB/s eta 0:00:02
   ----------- ---------------------------- 2.7/9.8 MB 8.3 MB/s eta 0:00:01
   ---------------- ----------------------- 4.1/9.8 MB 10.9 MB/s eta 0:00:01
   ------------------- -------------------- 4.7/9.8 MB 11.5 MB/s eta 0:00:01
   ------------------- -------------------- 4.7/9.8 MB 11.5 MB/s eta 0:00:01
   ------------------------------ --------- 7.6/9.8 MB 14.7 MB/s eta 0:00:01
   -------------------------------------- - 9.5/9.8 MB 16.4 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 16.1 MB/s eta 0:00:00
Downloading numpy-2.5.3-cp312-cp312-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.6 MB 42.3 MB/s eta 0:00:01
   ---- ----------------------------------- 1.5/12.6 MB 24.1 MB/s eta 0:00:01
   ---------- ----------------------------- 3.3/12.6 MB 23.1 MB/s eta 0:00:01
   ------------- -------------------------- 4.1/12.6 MB 21.9 MB/s eta 0:00:01
   --------------- ------------------------ 5.0/12.6 MB 21.3 MB/s eta 0:00:01
   ------------------ --------------------- 5.8/12.6 MB 19.6 MB/s eta 0:00:01
   -------------------- ------------------- 6.4/12.6 MB 19.5 MB/s eta 0:00:01
   ---------------------- ----------------- 7.2/12.6 MB 19.1 MB/s eta 0:00:01
   ------------------------- -------------- 8.0/12.6 MB 19.0 MB/s eta 0:00:01
   ---------------------------- ----------- 8.9/12.6 MB 18.4 MB/s eta 0:00:01
   ------------------------------- -------- 9.8/12.6 MB 18.9 MB/s eta 0:00:01
   --------------------------------- ------ 10.6/12.6 MB 18.7 MB/s eta 0:00:01
   ------------------------------------ --- 11.5/12.6 MB 17.2 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 18.7 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 17.7 MB/s eta 0:00:00
Downloading tzdata-2026.4-py2.py3-none-any.whl (347 kB)
   ---------------------------------------- 0.0/347.5 kB ? eta -:--:--
   --------------------------------------- 347.5/347.5 kB 22.5 MB/s eta 0:00:00
Installing collected packages: tzdata, numpy, pandas
Successfully installed numpy-2.5.3 pandas-3.0.5 tzdata-2026.4

[notice] A new release of pip is available: 23.3.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
   ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
   - -------------------------------------- 10.2/250.9 kB ? eta -:--:--
   ------ -------------------------------- 41.0/250.9 kB 495.5 kB/s eta 0:00:01
   ----------------- ---------------------- 112.6/250.9 kB 1.1 MB/s eta 0:00:01
   ------------------------------- -------- 194.6/250.9 kB 1.3 MB/s eta 0:00:01
   ---------------------------------------- 250.9/250.9 kB 1.5 MB/s eta 0:00:00
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 23.3.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
import pandas as pd

ARQUIVO_ENTRADA = 'CD2022_Populacao_2010_Compatibilizada_20231222.xlsx'

df = pd.read_excel(ARQUIVO_ENTRADA, sheet_name=0, skiprows=2)
df = df[df['COD. UF'].notna()].copy()
df.columns = ['IGNORAR', 'UF', 'COD_UF', 'COD_MUNIC', 'MUNICIPIO', 'POP_2010_SINOPSE', 'POP_2010_COMPATIBILIZADA', 'POP_2022']

col_2010 = 'POP_2010_COMPATIBILIZADA'
col_2022 = 'POP_2022'
df['Crescimento 2010-2022'] = df[col_2022] - df[col_2010]

df.head()

ModuleNotFoundError: No module named 'pandas'

In [2]:
populacao_estado = (
    df.groupby('UF')[[col_2010, col_2022, 'Crescimento 2010-2022']]
      .sum()
      .reset_index()
      .sort_values('Crescimento 2010-2022', ascending=False)
)

populacao_estado.to_csv('populacao_por_estado.csv', sep=';', index=False, encoding='utf-8-sig')
populacao_estado

    UF  POP_2010_COMPATIBILIZADA    POP_2022  Crescimento 2010-2022
25  SP                41262199.0  44411238.0              3149039.0
23  SC                 6248436.0   7610361.0              1361925.0
8   GO                 6001789.0   7056495.0              1054706.0
17  PR                10444526.0  11444380.0               999854.0
10  MG                19597330.0  20539989.0               942659.0
12  MT                 3035122.0   3658649.0               623527.0
13  PA                 7581051.0   8120131.0               539080.0
2   AM                 3483985.0   3941613.0               457628.0
5   CE                 8451644.0   8794957.0               343313.0
7   ES                 3514952.0   3833712.0               318760.0
11  MS                 2449024.0   2757013.0               307989.0
15  PE                 8796055.0   9058931.0               262876.0
6   DF                 2572159.0   2817381.0               245222.0
14  PB                 3766528.0   3974687.0               208159.0
9   MA                 6574789.0   6776699.0               201910.0
22  RS                10693929.0  10882965.0               189036.0
21  RR                  450479.0    636707.0               186228.0
16  PI                 3119097.0   3271199.0               152102.0
24  SE                 2067852.0   2210004.0               142152.0
19  RN                 3168027.0   3302729.0               134702.0
26  TO                 1383445.0   1511460.0               128015.0
4   BA                14017071.0  14141626.0               124555.0
0   AC                  733559.0    830018.0                96459.0
18  RJ                15989929.0  16055174.0                65245.0
3   AP                  669526.0    733759.0                64233.0
20  RO                 1562409.0   1581196.0                18787.0
1   AL                 3120887.0   3127683.0                 6796.0

In [3]:
populacao_municipio = (
    df[['UF', 'COD_UF', 'COD_MUNIC', 'MUNICIPIO', col_2010, col_2022, 'Crescimento 2010-2022']]
      .sort_values('Crescimento 2010-2022', ascending=False)
)

populacao_municipio.to_csv('populacao_por_municipio.csv', sep=';', index=False, encoding='utf-8-sig')
populacao_municipio.head()

,UF,COD_UF,COD_MUNIC,MUNICIPIO,POP_2010_COMPATIBILIZADA,POP_2022,Crescimento 2010-2022
111,AM,13.0,2603.0,Manaus,1802014.0,2063689.0,261675.0
5569,DF,53.0,108.0,Brasília,2572159.0,2817381.0,245222.0
3829,SP,35.0,50308.0,São Paulo,11253503.0,11451999.0,198496.0
3848,SP,35.0,52205.0,Sorocaba,586816.0,723682.0,136866.0
5417,GO,52.0,8707.0,Goiânia,1301912.0,1437366.0,135454.0